name: builder

on: [push, workflow_dispatch]

jobs:
  alpine:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v1
      -
        name: Login to Docker Hub
        run: echo "${{ secrets.REGISTRY_PASSWORD }}" | docker login -u "${{ secrets.REGISTRY_USERNAME }}" --password-stdin
        if: github.ref == 'refs/heads/main'
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
        with:
          platforms: all
      -
        name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1
        with:
          version: latest
      -
        name: List Available platforms
        run: echo ${{ steps.buildx.outputs.platforms }}
      -
        name: Run Buildx
        run: |
          docker buildx build \
            --platform linux/amd64,linux/arm64,linux/arm/v7 \
            --output "type=image,push=$([[ $GITHUB_REF == "refs/heads/main" ]] && echo true || echo false)" \
            -f Dockerfile -t jcxldn/mono:latest .
      -
        name: Run Buildx (apps/tshock)
        run: |
          docker buildx build \
            --platform linux/amd64,linux/arm64,linux/arm/v7 \
            --output "type=image,push=$([[ $GITHUB_REF == "refs/heads/main" ]] && echo true || echo false)" \
            -f apps/tshock/Dockerfile -t jcxldn/mono:tshock .